### ISSUE TITLE
RuntimeWarning: invalid value encountered in subtract   scores = scores - best_score

### ISSUE THREAD

**Issue by jzook** [nspies/genosv#44]
I get the error below on the variant HG2_PB_SVrefineFalcon1Dovetail_2831 when running the command below (you may want to select just this variant from the vcf for testing).

`genosv --outdir genosv20a1IllMPv030bPASSbionanodiffgt300 --ref /scratch/PI/msalit/jzook/references/human_g1k_v37.fasta -V /scratch/PI/msalit/jzook/AJTrio/svvizconfirm/union_170509/union_170509_refalt.2.2.2.clustered.simpleINFO.techcounts.bionanodiffgt300.vcf.gz /scratch/PI/msalit/jzook/AJTrio/IllMP/HG002_Ill_6kbMP_15x.bam
`

```
2017-08-31 02:39:50 - genosv.app.datahub        - INFO  - Working on HG2_PB_SVrefineFalcon1Dovetail_2831:SequenceDefinedVariant::6:31,279,007-31,305,730;len=16413
2017-08-31 02:39:50 - genosv.io.getreads        - INFO  - Loading more read pairs...
2017-08-31 02:39:58 - genosv.io.getreads        - INFO  - TIME to read batch: 8.7s
2017-08-31 02:39:58 - genosv.app.datahub        - INFO  - Analyzing 3579 read pairs

  0%|          | 0/3579 [00:00<?, ?it/s]
  1%|          | 35/3579 [00:00<00:10, 345.73it/s]
  2%|▏         | 74/3579 [00:00<00:09, 357.70it/s]
  3%|▎         | 119/3579 [00:00<00:09, 378.23it/s]
  5%|▍         | 173/3579 [00:00<00:08, 414.49it/s]
  6%|▌         | 208/3579 [00:00<00:09, 349.44it/s]
  7%|▋         | 259/3579 [00:00<00:08, 385.30it/s]
  8%|▊         | 297/3579 [00:00<00:08, 380.71it/s]
 10%|▉         | 347/3579 [00:00<00:07, 409.21it/s]
 11%|█         | 389/3579 [00:00<00:07, 408.72it/s]
 12%|█▏        | 443/3579 [00:01<00:07, 439.35it/s]
 14%|█▍        | 506/3579 [00:01<00:06, 483.09it/s]
 16%|█▌        | 557/3579 [00:01<00:06, 471.54it/s]
 17%|█▋        | 606/3579 [00:01<00:06, 446.52it/s]
 18%|█▊        | 654/3579 [00:01<00:06, 455.64it/s]
 20%|█▉        | 701/3579 [00:01<00:06, 419.04it/s]
 21%|██        | 745/3579 [00:01<00:06, 409.03it/s]
 22%|██▏       | 787/3579 [00:01<00:08, 332.31it/s]
 23%|██▎       | 824/3579 [00:02<00:11, 231.07it/s]
 24%|██▍       | 854/3579 [00:02<00:13, 199.90it/s]
 25%|██▍       | 880/3579 [00:02<00:12, 213.21it/s]
 25%|██▌       | 906/3579 [00:02<00:12, 208.48it/s]
 26%|██▋       | 941/3579 [00:02<00:11, 236.42it/s]
 27%|██▋       | 970/3579 [00:02<00:10, 248.78it/s]/home/jzook/svviz2test343/genosv/src/genosv/remap/alignment.py:246: RuntimeWarning: invalid value encountered in subtract
  scores = scores - best_score

Traceback (most recent call last):
  File "/home/jzook/svviz2test343/bin/genosv", line 11, in <module>
    load_entry_point('genosv', 'console_scripts', 'genosv')()
  File "/home/jzook/svviz2test343/genosv/src/genosv/app/main.py", line 60, in main
    run(datahub)
  File "/home/jzook/svviz2test343/genosv/src/genosv/app/main.py", line 41, in run
    datahub.genotype_cur_variant()
  File "/home/jzook/svviz2test343/genosv/src/genosv/app/datahub.py", line 116, in genotype_cur_variant
    aln_sets = maprealign.map_realign(batch, self, sample)
  File "/home/jzook/svviz2test343/genosv/src/genosv/remap/maprealign.py", line 6, in map_realign
    return map_realign_pairs(batch, realigner, sample)
  File "/home/jzook/svviz2test343/genosv/src/genosv/remap/maprealign.py", line 22, in map_realign_pairs
    read_or_pair.realign(ref_genome_sources, alt_genome_sources)
  File "/home/jzook/svviz2test343/genosv/src/genosv/remap/readpair.py", line 60, in realign
    alignment.set_mapqs(self.ref_pairs+self.alt_pairs)
  File "/home/jzook/svviz2test343/genosv/src/genosv/remap/alignment.py", line 256, in set_mapqs
    aln.mapq = int(min(prob_to_phred(1-aln.posterior, 10), 40))
ValueError: cannot convert float NaN to integer

```

**Comment by nspies** [comment]
not quite right...
